# Generated by Django 5.0 on 2023-12-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='Court',
        ),
    ]
