# Generated by Django 5.0 on 2023-12-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_field_court'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='type',
            new_name='types',
        ),
    ]
